version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    image: japostol/wiregoose:backend
    depends_on:
      - mongo
    volumes:
      - /usr/src/wiregoose/logs:/logs
    ports:
      - '5001:5001'
    env_file:
      - ./.env.production
    links:
      - mongo

  crawler:
    build:
      context: ./
      dockerfile: ./deploy/crawler/Dockerfile
    image: japostol/wiregoose:crawler
    depends_on:
      - mongo
    env_file:
      - ./.env.production
    volumes:
      - /usr/src/wiregoose/logs:/logs
    links:
      - mongo

  proxy:
    build:
      context: .
      dockerfile: ./deploy/imageProxy/Dockerfile
    image: japostol/wiregoose:proxy
    volumes:
      - /usr/src/wiregoose/logs:/logs
    ports:
      - '5002:5002'
    env_file:
      - ./.env.production

  ssr:
    build:
      context: .
      dockerfile: ./deploy/ssr/Dockerfile
    image: japostol/wiregoose:ssr
    volumes:
      - /usr/src/wiregoose/logs:/logs
    ports:
      - '5004:5004'
    env_file:
      - ./.env.production

  mongo:
    image: mongo
    volumes:
      - /usr/src/wiregoose/data:/data/db
    ports:
      - '5003:27017'
