version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./logs:/logs
    ports:
      - '4200:4200'
    env_file:
      - ./.env.production
    links:
      - mongo

  crawler:
    build:
      context: ./
      dockerfile: ./deploy/crawler/Dockerfile
    depends_on:
      - mongo
    env_file:
      - ./.env.production
    volumes:
      - ./logs:/logs
    links:
      - mongo

  proxy:
    build:
      context: .
      dockerfile: ./deploy/imageProxy/Dockerfile
    volumes:
      - ./logs:/logs
    ports:
      - '4011:4011'
    env_file:
      - ./.env.production

  mongo:
    image: mongo
    volumes:
      - /Users/yannis/Documents/wiregoose2/data:/data/db
    ports:
      - '27017:27017'
